import 'package:alloc/app/shared/enums/tipo_ativo_enum.dart';
import 'package:alloc/app/shared/models/evento_provento.dart';
import 'package:alloc/app/shared/utils/date_util.dart';

class BackupProventos {
  static List<EventoProvento> getProventos() {
    String carteiraPrincipal = "eyyokB82WciaQB1vf0C4";
    String usuarioId = "7zNUkD8laqglbKVgD1nc1o9zcJ72";

    return [
      EventoProvento(null, DateUtil.StringToDate("15/04/2020").millisecondsSinceEpoch,
          carteiraPrincipal, usuarioId, 2.32, 4, "XPLG11"),
      EventoProvento(null, DateUtil.StringToDate("15/05/2020").millisecondsSinceEpoch,
          carteiraPrincipal, usuarioId, 2.16, 4, "XPLG11"),
      EventoProvento(null, DateUtil.StringToDate("15/06/2020").millisecondsSinceEpoch,
          carteiraPrincipal, usuarioId, 2.16, 4, "XPLG11"),
      EventoProvento(null, DateUtil.StringToDate("15/07/2020").millisecondsSinceEpoch,
          carteiraPrincipal, usuarioId, 2.28, 4, "XPLG11"),
      EventoProvento(null, DateUtil.StringToDate("15/08/2020").millisecondsSinceEpoch,
          carteiraPrincipal, usuarioId, 2.32, 4, "XPLG11"),
      EventoProvento(null, DateUtil.StringToDate("15/09/2020").millisecondsSinceEpoch,
          carteiraPrincipal, usuarioId, 2.32, 4, "XPLG11"),
      EventoProvento(null, DateUtil.StringToDate("15/10/2020").millisecondsSinceEpoch,
          carteiraPrincipal, usuarioId, 2.32, 4, "XPLG11"),
      EventoProvento(null, DateUtil.StringToDate("15/11/2020").millisecondsSinceEpoch,
          carteiraPrincipal, usuarioId, 2.32, 4, "XPLG11"),
      EventoProvento(null, DateUtil.StringToDate("15/12/2020").millisecondsSinceEpoch,
          carteiraPrincipal, usuarioId, 2.32, 4, "XPLG11"),
      EventoProvento(null, DateUtil.StringToDate("15/01/2021").millisecondsSinceEpoch,
          carteiraPrincipal, usuarioId, 2.40, 4, "XPLG11"),
      EventoProvento(null, DateUtil.StringToDate("15/02/2021").millisecondsSinceEpoch,
          carteiraPrincipal, usuarioId, 2.32, 4, "XPLG11"),
      EventoProvento(null, DateUtil.StringToDate("15/03/2021").millisecondsSinceEpoch,
          carteiraPrincipal, usuarioId, 2.32, 4, "XPLG11"),
      EventoProvento(null, DateUtil.StringToDate("15/04/2020").millisecondsSinceEpoch,
          carteiraPrincipal, usuarioId, 1.20, 4, "VISC11"),
      EventoProvento(null, DateUtil.StringToDate("15/05/2020").millisecondsSinceEpoch,
          carteiraPrincipal, usuarioId, 1.08, 4, "VISC11"),
      EventoProvento(null, DateUtil.StringToDate("15/06/2020").millisecondsSinceEpoch,
          carteiraPrincipal, usuarioId, 0.92, 4, "VISC11"),
      EventoProvento(null, DateUtil.StringToDate("15/07/2020").millisecondsSinceEpoch,
          carteiraPrincipal, usuarioId, 0.76, 4, "VISC11"),
      EventoProvento(null, DateUtil.StringToDate("15/08/2020").millisecondsSinceEpoch,
          carteiraPrincipal, usuarioId, 0.72, 4, "VISC11"),
      EventoProvento(null, DateUtil.StringToDate("15/09/2020").millisecondsSinceEpoch,
          carteiraPrincipal, usuarioId, 0.90, 4, "VISC11"),
      EventoProvento(null, DateUtil.StringToDate("15/10/2020").millisecondsSinceEpoch,
          carteiraPrincipal, usuarioId, 1.20, 6, "VISC11"),
      EventoProvento(null, DateUtil.StringToDate("15/11/2020").millisecondsSinceEpoch,
          carteiraPrincipal, usuarioId, 2.24, 6, "VISC11"),
      EventoProvento(null, DateUtil.StringToDate("15/12/2020").millisecondsSinceEpoch,
          carteiraPrincipal, usuarioId, 3.60, 8, "VISC11"),
      EventoProvento(null, DateUtil.StringToDate("15/01/2021").millisecondsSinceEpoch,
          carteiraPrincipal, usuarioId, 4.40, 8, "VISC11"),
      EventoProvento(null, DateUtil.StringToDate("15/02/2021").millisecondsSinceEpoch,
          carteiraPrincipal, usuarioId, 4.80, 8, "VISC11"),
      EventoProvento(null, DateUtil.StringToDate("15/03/2021").millisecondsSinceEpoch,
          carteiraPrincipal, usuarioId, 4.40, 8, "VISC11"),
      EventoProvento(null, DateUtil.StringToDate("15/04/2020").millisecondsSinceEpoch,
          carteiraPrincipal, usuarioId, 1.80, 3, "LVBI11"),
      EventoProvento(null, DateUtil.StringToDate("15/05/2020").millisecondsSinceEpoch,
          carteiraPrincipal, usuarioId, 1.80, 3, "LVBI11"),
      EventoProvento(null, DateUtil.StringToDate("15/06/2020").millisecondsSinceEpoch,
          carteiraPrincipal, usuarioId, 1.80, 3, "LVBI11"),
      EventoProvento(null, DateUtil.StringToDate("15/07/2020").millisecondsSinceEpoch,
          carteiraPrincipal, usuarioId, 2.01, 3, "LVBI11"),
      EventoProvento(null, DateUtil.StringToDate("15/08/2020").millisecondsSinceEpoch,
          carteiraPrincipal, usuarioId, 2.06, 3, "LVBI11"),
      EventoProvento(null, DateUtil.StringToDate("15/09/2020").millisecondsSinceEpoch,
          carteiraPrincipal, usuarioId, 2.01, 3, "LVBI11"),
      EventoProvento(null, DateUtil.StringToDate("15/10/2020").millisecondsSinceEpoch,
          carteiraPrincipal, usuarioId, 1.98, 3, "LVBI11"),
      EventoProvento(null, DateUtil.StringToDate("15/11/2020").millisecondsSinceEpoch,
          carteiraPrincipal, usuarioId, 0.93, 3, "LVBI11"),
      EventoProvento(null, DateUtil.StringToDate("15/12/2020").millisecondsSinceEpoch,
          carteiraPrincipal, usuarioId, 1.08, 3, "LVBI11"),
      EventoProvento(null, DateUtil.StringToDate("15/01/2021").millisecondsSinceEpoch,
          carteiraPrincipal, usuarioId, 1.41, 3, "LVBI11"),
      EventoProvento(null, DateUtil.StringToDate("15/02/2021").millisecondsSinceEpoch,
          carteiraPrincipal, usuarioId, 1.56, 3, "LVBI11"),
      EventoProvento(null, DateUtil.StringToDate("15/03/2021").millisecondsSinceEpoch,
          carteiraPrincipal, usuarioId, 1.41, 3, "LVBI11"),
      EventoProvento(null, DateUtil.StringToDate("15/04/2020").millisecondsSinceEpoch,
          carteiraPrincipal, usuarioId, 0.40, 1, "MALL11"),
      EventoProvento(null, DateUtil.StringToDate("15/05/2020").millisecondsSinceEpoch,
          carteiraPrincipal, usuarioId, 0.12, 1, "MALL11"),
      EventoProvento(null, DateUtil.StringToDate("15/06/2020").millisecondsSinceEpoch,
          carteiraPrincipal, usuarioId, 0.11, 1, "MALL11"),
      EventoProvento(null, DateUtil.StringToDate("15/07/2020").millisecondsSinceEpoch,
          carteiraPrincipal, usuarioId, 0.14, 1, "MALL11"),
      EventoProvento(null, DateUtil.StringToDate("15/08/2020").millisecondsSinceEpoch,
          carteiraPrincipal, usuarioId, 0.15, 1, "MALL11"),
      EventoProvento(null, DateUtil.StringToDate("15/09/2020").millisecondsSinceEpoch,
          carteiraPrincipal, usuarioId, 0.30, 1, "MALL11"),
      EventoProvento(null, DateUtil.StringToDate("15/10/2020").millisecondsSinceEpoch,
          carteiraPrincipal, usuarioId, 2.10, 6, "MALL11"),
      EventoProvento(null, DateUtil.StringToDate("15/11/2020").millisecondsSinceEpoch,
          carteiraPrincipal, usuarioId, 2.88, 6, "MALL11"),
      EventoProvento(null, DateUtil.StringToDate("15/12/2020").millisecondsSinceEpoch,
          carteiraPrincipal, usuarioId, 4.06, 7, "MALL11"),
      EventoProvento(null, DateUtil.StringToDate("15/01/2021").millisecondsSinceEpoch,
          carteiraPrincipal, usuarioId, 4.34, 7, "MALL11"),
      EventoProvento(null, DateUtil.StringToDate("15/02/2021").millisecondsSinceEpoch,
          carteiraPrincipal, usuarioId, 4.34, 7, "MALL11"),
      EventoProvento(null, DateUtil.StringToDate("15/03/2021").millisecondsSinceEpoch,
          carteiraPrincipal, usuarioId, 4.20, 7, "MALL11"),
      EventoProvento(null, DateUtil.StringToDate("15/04/2020").millisecondsSinceEpoch,
          carteiraPrincipal, usuarioId, 0.81, 1, "RECT11"),
      EventoProvento(null, DateUtil.StringToDate("15/05/2020").millisecondsSinceEpoch,
          carteiraPrincipal, usuarioId, 0.81, 1, "RECT11"),
      EventoProvento(null, DateUtil.StringToDate("15/06/2020").millisecondsSinceEpoch,
          carteiraPrincipal, usuarioId, 0.81, 1, "RECT11"),
      EventoProvento(null, DateUtil.StringToDate("15/07/2020").millisecondsSinceEpoch,
          carteiraPrincipal, usuarioId, 0.81, 1, "RECT11"),
      EventoProvento(null, DateUtil.StringToDate("15/08/2020").millisecondsSinceEpoch,
          carteiraPrincipal, usuarioId, 0.81, 1, "RECT11"),
      EventoProvento(null, DateUtil.StringToDate("15/09/2020").millisecondsSinceEpoch,
          carteiraPrincipal, usuarioId, 7.92, 11, "RECT11"),
      EventoProvento(null, DateUtil.StringToDate("15/10/2020").millisecondsSinceEpoch,
          carteiraPrincipal, usuarioId, 7.92, 11, "RECT11"),
      EventoProvento(null, DateUtil.StringToDate("15/11/2020").millisecondsSinceEpoch,
          carteiraPrincipal, usuarioId, 7.92, 11, "RECT11"),
      EventoProvento(null, DateUtil.StringToDate("15/12/2020").millisecondsSinceEpoch,
          carteiraPrincipal, usuarioId, 7.92, 11, "RECT11"),
      EventoProvento(null, DateUtil.StringToDate("15/01/2021").millisecondsSinceEpoch,
          carteiraPrincipal, usuarioId, 7.92, 11, "RECT11"),
      EventoProvento(null, DateUtil.StringToDate("15/02/2021").millisecondsSinceEpoch,
          carteiraPrincipal, usuarioId, 7.92, 11, "RECT11"),
      EventoProvento(null, DateUtil.StringToDate("15/10/2020").millisecondsSinceEpoch,
          carteiraPrincipal, usuarioId, 7.50, 10, "CVBI11"),
      EventoProvento(null, DateUtil.StringToDate("15/11/2020").millisecondsSinceEpoch,
          carteiraPrincipal, usuarioId, 10.00, 10, "CVBI11"),
      EventoProvento(null, DateUtil.StringToDate("15/12/2020").millisecondsSinceEpoch,
          carteiraPrincipal, usuarioId, 25.50, 17, "CVBI11"),
      EventoProvento(null, DateUtil.StringToDate("15/01/2021").millisecondsSinceEpoch,
          carteiraPrincipal, usuarioId, 33.15, 17, "CVBI11"),
      EventoProvento(null, DateUtil.StringToDate("15/02/2021").millisecondsSinceEpoch,
          carteiraPrincipal, usuarioId, 21.08, 17, "CVBI11"),
      EventoProvento(null, DateUtil.StringToDate("15/03/2021").millisecondsSinceEpoch,
          carteiraPrincipal, usuarioId, 21.08, 17, "CVBI11"),
      EventoProvento(null, DateUtil.StringToDate("15/10/2020").millisecondsSinceEpoch,
          carteiraPrincipal, usuarioId, 6.26, 14, "BRCR11"),
      EventoProvento(null, DateUtil.StringToDate("15/11/2020").millisecondsSinceEpoch,
          carteiraPrincipal, usuarioId, 6.59, 14, "BRCR11"),
      EventoProvento(null, DateUtil.StringToDate("15/12/2020").millisecondsSinceEpoch,
          carteiraPrincipal, usuarioId, 9.98, 20, "BRCR11"),
      EventoProvento(null, DateUtil.StringToDate("15/01/2021").millisecondsSinceEpoch,
          carteiraPrincipal, usuarioId, 10.00, 20, "BRCR11"),
      EventoProvento(null, DateUtil.StringToDate("15/02/2021").millisecondsSinceEpoch,
          carteiraPrincipal, usuarioId, 9.80, 20, "BRCR11"),
      EventoProvento(null, DateUtil.StringToDate("15/03/2021").millisecondsSinceEpoch,
          carteiraPrincipal, usuarioId, 10.56, 22, "BRCR11"),
      EventoProvento(null, DateUtil.StringToDate("15/04/2020").millisecondsSinceEpoch,
          carteiraPrincipal, usuarioId, 0.65, 1, "HGRE11"),
      EventoProvento(null, DateUtil.StringToDate("15/05/2020").millisecondsSinceEpoch,
          carteiraPrincipal, usuarioId, 3.42, 6, "HGRE11"),
      EventoProvento(null, DateUtil.StringToDate("15/06/2020").millisecondsSinceEpoch,
          carteiraPrincipal, usuarioId, 3.42, 6, "HGRE11"),
      EventoProvento(null, DateUtil.StringToDate("15/07/2020").millisecondsSinceEpoch,
          carteiraPrincipal, usuarioId, 3.42, 6, "HGRE11"),
      EventoProvento(null, DateUtil.StringToDate("15/08/2020").millisecondsSinceEpoch,
          carteiraPrincipal, usuarioId, 3.90, 6, "HGRE11"),
      EventoProvento(null, DateUtil.StringToDate("15/09/2020").millisecondsSinceEpoch,
          carteiraPrincipal, usuarioId, 3.90, 6, "HGRE11"),
      EventoProvento(null, DateUtil.StringToDate("15/10/2020").millisecondsSinceEpoch,
          carteiraPrincipal, usuarioId, 3.90, 6, "HGRE11"),
      EventoProvento(null, DateUtil.StringToDate("15/11/2020").millisecondsSinceEpoch,
          carteiraPrincipal, usuarioId, 3.90, 6, "HGRE11"),
      EventoProvento(null, DateUtil.StringToDate("15/12/2020").millisecondsSinceEpoch,
          carteiraPrincipal, usuarioId, 9.10, 14, "HGRE11"),
      EventoProvento(null, DateUtil.StringToDate("15/01/2021").millisecondsSinceEpoch,
          carteiraPrincipal, usuarioId, 13.58, 14, "HGRE11"),
      EventoProvento(null, DateUtil.StringToDate("15/02/2021").millisecondsSinceEpoch,
          carteiraPrincipal, usuarioId, 9.38, 14, "HGRE11"),
      EventoProvento(null, DateUtil.StringToDate("15/03/2021").millisecondsSinceEpoch,
          carteiraPrincipal, usuarioId, 9.38, 14, "HGRE11"),
      EventoProvento(null, DateUtil.StringToDate("15/04/2020").millisecondsSinceEpoch,
          carteiraPrincipal, usuarioId, 0.75, 1, "RCRB11"),
      EventoProvento(null, DateUtil.StringToDate("15/05/2020").millisecondsSinceEpoch,
          carteiraPrincipal, usuarioId, 0.75, 1, "RCRB11"),
      EventoProvento(null, DateUtil.StringToDate("15/06/2020").millisecondsSinceEpoch,
          carteiraPrincipal, usuarioId, 1.55, 1, "RCRB11"),
      EventoProvento(null, DateUtil.StringToDate("15/07/2020").millisecondsSinceEpoch,
          carteiraPrincipal, usuarioId, 0.80, 1, "RCRB11"),
      EventoProvento(null, DateUtil.StringToDate("15/08/2020").millisecondsSinceEpoch,
          carteiraPrincipal, usuarioId, 0.85, 1, "RCRB11"),
      EventoProvento(null, DateUtil.StringToDate("15/09/2020").millisecondsSinceEpoch,
          carteiraPrincipal, usuarioId, 0.85, 1, "RCRB11"),
      EventoProvento(null, DateUtil.StringToDate("15/10/2020").millisecondsSinceEpoch,
          carteiraPrincipal, usuarioId, 0.85, 1, "RCRB11"),
      EventoProvento(null, DateUtil.StringToDate("15/11/2020").millisecondsSinceEpoch,
          carteiraPrincipal, usuarioId, 0.85, 1, "RCRB11"),
      EventoProvento(null, DateUtil.StringToDate("15/12/2020").millisecondsSinceEpoch,
          carteiraPrincipal, usuarioId, 0.85, 1, "RCRB11"),
      EventoProvento(null, DateUtil.StringToDate("15/01/2021").millisecondsSinceEpoch,
          carteiraPrincipal, usuarioId, 0.80, 1, "RCRB11"),
      EventoProvento(null, DateUtil.StringToDate("15/02/2021").millisecondsSinceEpoch,
          carteiraPrincipal, usuarioId, 0.80, 1, "RCRB11"),
      EventoProvento(null, DateUtil.StringToDate("15/03/2021").millisecondsSinceEpoch,
          carteiraPrincipal, usuarioId, 8.80, 11, "RCRB11"),
      EventoProvento(null, DateUtil.StringToDate("15/04/2020").millisecondsSinceEpoch,
          carteiraPrincipal, usuarioId, 0.90, 1, "HGBS11"),
      EventoProvento(null, DateUtil.StringToDate("15/05/2020").millisecondsSinceEpoch,
          carteiraPrincipal, usuarioId, 0.35, 1, "HGBS11"),
      EventoProvento(null, DateUtil.StringToDate("15/06/2020").millisecondsSinceEpoch,
          carteiraPrincipal, usuarioId, 0.35, 1, "HGBS11"),
      EventoProvento(null, DateUtil.StringToDate("15/07/2020").millisecondsSinceEpoch,
          carteiraPrincipal, usuarioId, 0.35, 1, "HGBS11"),
      EventoProvento(null, DateUtil.StringToDate("15/08/2020").millisecondsSinceEpoch,
          carteiraPrincipal, usuarioId, 0.25, 1, "HGBS11"),
      EventoProvento(null, DateUtil.StringToDate("15/09/2020").millisecondsSinceEpoch,
          carteiraPrincipal, usuarioId, 0.50, 2, "HGBS11"),
      EventoProvento(null, DateUtil.StringToDate("15/10/2020").millisecondsSinceEpoch,
          carteiraPrincipal, usuarioId, 0.90, 3, "HGBS11"),
      EventoProvento(null, DateUtil.StringToDate("15/11/2020").millisecondsSinceEpoch,
          carteiraPrincipal, usuarioId, 1.20, 3, "HGBS11"),
      EventoProvento(null, DateUtil.StringToDate("15/12/2020").millisecondsSinceEpoch,
          carteiraPrincipal, usuarioId, 3.60, 6, "HGBS11"),
      EventoProvento(null, DateUtil.StringToDate("15/01/2021").millisecondsSinceEpoch,
          carteiraPrincipal, usuarioId, 3.96, 6, "HGBS11"),
      EventoProvento(null, DateUtil.StringToDate("15/02/2021").millisecondsSinceEpoch,
          carteiraPrincipal, usuarioId, 4.80, 6, "HGBS11"),
      EventoProvento(null, DateUtil.StringToDate("15/03/2021").millisecondsSinceEpoch,
          carteiraPrincipal, usuarioId, 4.80, 6, "HGBS11"),
      EventoProvento(null, DateUtil.StringToDate("15/04/2020").millisecondsSinceEpoch,
          carteiraPrincipal, usuarioId, 1.00, 2, "BTLG11"),
      EventoProvento(null, DateUtil.StringToDate("15/05/2020").millisecondsSinceEpoch,
          carteiraPrincipal, usuarioId, 1.00, 2, "BTLG11"),
      EventoProvento(null, DateUtil.StringToDate("15/06/2020").millisecondsSinceEpoch,
          carteiraPrincipal, usuarioId, 1.00, 2, "BTLG11"),
      EventoProvento(null, DateUtil.StringToDate("15/07/2020").millisecondsSinceEpoch,
          carteiraPrincipal, usuarioId, 1.00, 2, "BTLG11"),
      EventoProvento(null, DateUtil.StringToDate("15/08/2020").millisecondsSinceEpoch,
          carteiraPrincipal, usuarioId, 1.00, 2, "BTLG11"),
      EventoProvento(null, DateUtil.StringToDate("15/09/2020").millisecondsSinceEpoch,
          carteiraPrincipal, usuarioId, 0.66, 2, "BTLG11"),
      EventoProvento(null, DateUtil.StringToDate("15/10/2020").millisecondsSinceEpoch,
          carteiraPrincipal, usuarioId, 4.80, 8, "BTLG11"),
      EventoProvento(null, DateUtil.StringToDate("15/11/2020").millisecondsSinceEpoch,
          carteiraPrincipal, usuarioId, 4.80, 8, "BTLG11"),
      EventoProvento(null, DateUtil.StringToDate("15/12/2020").millisecondsSinceEpoch,
          carteiraPrincipal, usuarioId, 4.80, 8, "BTLG11"),
      EventoProvento(null, DateUtil.StringToDate("15/01/2021").millisecondsSinceEpoch,
          carteiraPrincipal, usuarioId, 10.80, 18, "BTLG11"),
      EventoProvento(null, DateUtil.StringToDate("15/02/2021").millisecondsSinceEpoch,
          carteiraPrincipal, usuarioId, 10.80, 18, "BTLG11"),
      EventoProvento(null, DateUtil.StringToDate("15/03/2021").millisecondsSinceEpoch,
          carteiraPrincipal, usuarioId, 10.80, 18, "BTLG11"),
      EventoProvento(null, DateUtil.StringToDate("15/06/2020").millisecondsSinceEpoch,
          carteiraPrincipal, usuarioId, 2.80, 8, "VINO11"),
      EventoProvento(null, DateUtil.StringToDate("15/07/2020").millisecondsSinceEpoch,
          carteiraPrincipal, usuarioId, 3.36, 8, "VINO11"),
      EventoProvento(null, DateUtil.StringToDate("15/08/2020").millisecondsSinceEpoch,
          carteiraPrincipal, usuarioId, 2.88, 8, "VINO11"),
      EventoProvento(null, DateUtil.StringToDate("15/09/2020").millisecondsSinceEpoch,
          carteiraPrincipal, usuarioId, 2.80, 8, "VINO11"),
      EventoProvento(null, DateUtil.StringToDate("15/10/2020").millisecondsSinceEpoch,
          carteiraPrincipal, usuarioId, 2.80, 8, "VINO11"),
      EventoProvento(null, DateUtil.StringToDate("15/11/2020").millisecondsSinceEpoch,
          carteiraPrincipal, usuarioId, 2.80, 8, "VINO11"),
      EventoProvento(null, DateUtil.StringToDate("15/12/2020").millisecondsSinceEpoch,
          carteiraPrincipal, usuarioId, 2.80, 8, "VINO11"),
      EventoProvento(null, DateUtil.StringToDate("15/01/2021").millisecondsSinceEpoch,
          carteiraPrincipal, usuarioId, 3.36, 8, "VINO11"),
      EventoProvento(null, DateUtil.StringToDate("15/02/2021").millisecondsSinceEpoch,
          carteiraPrincipal, usuarioId, 3.60, 8, "VINO11"),
      EventoProvento(null, DateUtil.StringToDate("15/03/2021").millisecondsSinceEpoch,
          carteiraPrincipal, usuarioId, 3.60, 8, "VINO11"),
      EventoProvento(null, DateUtil.StringToDate("15/10/2020").millisecondsSinceEpoch,
          carteiraPrincipal, usuarioId, 3.28, 4, "PORD11"),
      EventoProvento(null, DateUtil.StringToDate("15/11/2020").millisecondsSinceEpoch,
          carteiraPrincipal, usuarioId, 3.20, 4, "PORD11"),
      EventoProvento(null, DateUtil.StringToDate("15/12/2020").millisecondsSinceEpoch,
          carteiraPrincipal, usuarioId, 3.24, 4, "PORD11"),
      EventoProvento(null, DateUtil.StringToDate("15/01/2021").millisecondsSinceEpoch,
          carteiraPrincipal, usuarioId, 4.12, 4, "PORD11"),
      EventoProvento(null, DateUtil.StringToDate("15/02/2021").millisecondsSinceEpoch,
          carteiraPrincipal, usuarioId, 3.24, 4, "PORD11"),
      EventoProvento(null, DateUtil.StringToDate("15/03/2021").millisecondsSinceEpoch,
          carteiraPrincipal, usuarioId, 3.36, 4, "PORD11"),
      EventoProvento(null, DateUtil.StringToDate("15/09/2020").millisecondsSinceEpoch,
          carteiraPrincipal, usuarioId, 4.50, 9, "CPFF11"),
      EventoProvento(null, DateUtil.StringToDate("15/10/2020").millisecondsSinceEpoch,
          carteiraPrincipal, usuarioId, 4.95, 9, "CPFF11"),
      EventoProvento(null, DateUtil.StringToDate("15/11/2020").millisecondsSinceEpoch,
          carteiraPrincipal, usuarioId, 5.40, 9, "CPFF11"),
      EventoProvento(null, DateUtil.StringToDate("15/12/2020").millisecondsSinceEpoch,
          carteiraPrincipal, usuarioId, 5.85, 9, "CPFF11"),
      EventoProvento(null, DateUtil.StringToDate("15/01/2021").millisecondsSinceEpoch,
          carteiraPrincipal, usuarioId, 8.64, 9, "CPFF11"),
      EventoProvento(null, DateUtil.StringToDate("15/02/2021").millisecondsSinceEpoch,
          carteiraPrincipal, usuarioId, 7.20, 9, "CPFF11"),
      EventoProvento(null, DateUtil.StringToDate("15/03/2021").millisecondsSinceEpoch,
          carteiraPrincipal, usuarioId, 16.80, 21, "CPFF11"),
      EventoProvento(null, DateUtil.StringToDate("15/07/2020").millisecondsSinceEpoch,
          carteiraPrincipal, usuarioId, 1.00, 50, "ITSA3"),
      EventoProvento(null, DateUtil.StringToDate("15/08/2020").millisecondsSinceEpoch,
          carteiraPrincipal, usuarioId, 1.00, 50, "ITSA3"),
      EventoProvento(null, DateUtil.StringToDate("15/10/2020").millisecondsSinceEpoch,
          carteiraPrincipal, usuarioId, 1.18, 50, "ITSA3"),
      EventoProvento(null, DateUtil.StringToDate("15/01/2021").millisecondsSinceEpoch,
          carteiraPrincipal, usuarioId, 1.00, 50, "ITSA3"),
      EventoProvento(null, DateUtil.StringToDate("15/03/2021").millisecondsSinceEpoch,
          carteiraPrincipal, usuarioId, 5.21, 50, "ITSA3"),
      EventoProvento(null, DateUtil.StringToDate("15/08/2020").millisecondsSinceEpoch,
          carteiraPrincipal, usuarioId, 8.11, 31, "TAEE3"),
      EventoProvento(null, DateUtil.StringToDate("15/11/2020").millisecondsSinceEpoch,
          carteiraPrincipal, usuarioId, 13.81, 31, "TAEE3"),
      EventoProvento(null, DateUtil.StringToDate("15/12/2020").millisecondsSinceEpoch,
          carteiraPrincipal, usuarioId, 1.56, 35, "TAEE3"),
      EventoProvento(null, DateUtil.StringToDate("15/11/2020").millisecondsSinceEpoch,
          carteiraPrincipal, usuarioId, 3.33, 19, "TIMS3"),
      EventoProvento(null, DateUtil.StringToDate("15/01/2021").millisecondsSinceEpoch,
          carteiraPrincipal, usuarioId, 5.40, 27, "TIMS3"),
      EventoProvento(null, DateUtil.StringToDate("15/01/2021").millisecondsSinceEpoch,
          carteiraPrincipal, usuarioId, 3.83, 50, "ABEV3"),
      EventoProvento(null, DateUtil.StringToDate("15/03/2021").millisecondsSinceEpoch,
          carteiraPrincipal, usuarioId, 7.39, 20, "BBAS3"),
      EventoProvento(null, DateUtil.StringToDate("15/03/2021").millisecondsSinceEpoch,
          carteiraPrincipal, usuarioId, 6.15, 151, "RANI3"),
      EventoProvento(null, DateUtil.StringToDate("15/03/2021").millisecondsSinceEpoch,
          carteiraPrincipal, usuarioId, 8.53, 78, "GOAU3"),
    ];
  }
}
